- hosts: all
  tasks:
  - name: Upgrade apt packages
    become: true
    apt:
      upgrade: yes

  - name: Install list of packages
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
      state: present
    retries: 3
    delay: 5

  - name: Pause for 5 minutes to build app cache
    pause:
      minutes: 2  

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    retries: 3
    delay: 3

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install list of packages
    apt:
      name: ['docker-ce','docker-ce-cli', 'containerd.io']
      state: present
    retries: 3
    delay: 5      